name: Test

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,15 * *' # JST 9:00 on 1st and 15th every month

jobs:
  main:
    strategy:
      matrix:
        # os: ['ubuntu-22.04']
        python-version: ['3.9', '3.12']
        numpy-version: ['1.21.6', 'latest']
        exclude:
          - python-version: '3.12'
            numpy-version: '1.21.6'
      fail-fast: false

    name: Run tests with Python ${{ matrix.python-version }} and NumPy ${{ matrix.numpy-version }}
    runs-on: 'ubuntu-22.04'
    # runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: apt
        run: |
          sudo apt update
          sudo apt install openmpi-bin libopenmpi-dev

      - name: pip
        run: |
          python -m pip install -U pip
          python -m pip install setuptools wheel
          if [ "${{ matrix.numpy-version }}" = "latest" ]; then
            python -m pip install numpy
          else
            python -m pip install "numpy==${{ matrix.numpy-version }}"
          fi
          python -m pip install scipy tomli mpi4py
          python -m pip install physbo

      - name: run
        run: |
          mkdir build && cd build && cmake ..
          ctest -V
